FROM phpdockerio/php:8.3-fpm
WORKDIR "/application"

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
        git \ 
        php8.3-decimal \ 
        php8.3-gd \ 
        php8.3-http \ 
        php8.3-memcached \ 
        php8.3-mysql \ 
        php8.3-redis \ 
        php8.3-xdebug \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
